version: '3'
services:
  mysql:
    image: mysql:8-oracle
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=moov
      - MYSQL_USER=moov
      - MYSQL_PASSWORD=moov
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - intranet
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    tmpfs: # Run this mysql in memory as its used for testing
      - /var/lib/mysql

networks:
  intranet:
